### ISSUE TITLE
ChatPrototype Activity: issue in UI

### ISSUE THREAD

**Issue by VedantSharma11** [llaske/sugarizer#1331]
### Reference Video:
---

https://user-images.githubusercontent.com/96445392/225383652-4bfbc5a3-2be5-4907-adc9-0852d3ed7a17.mp4

**Comment by llaske** [comment]
Chat activity UI need to be rethink, I'm not in favor of doing minor style change.

**Comment by VedantSharma11** [comment]
@llaske I agree that a more better approach may be required to improve the user experience. I was wondering if you could provide more information on what areas you think I could focus on to improve the chat activity UI.

**Comment by Shreyas-SAS** [comment]
Hey! @llaske would you mind if I propose some designs for ChatPrototype Activity? 

I will redesign it if we can reach a conclusion. I am anyways NOT working for GSOC this year, so was waiting for the submission period to end before making any contributions to SugarLabs, so that I don't snatch someone's contribution opportunity unknowingly.  But since this is too large of an Issue, I don't think that those aiming for GSOC wanted to continue with this in the short period left.

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS Yes you could suggest something.

Okay. I will share some figma/photoshop designs here for your approval.

**Comment by llaske** [comment]
Some proposals and discussions here https://discordapp.com/channels/1078051575580336249/1078053527269675039/1097268214263713942

**Comment by Shreyas-SAS** [comment]
Oh great @llaske, I will refer to them and try to come up with a final design. Got delayed a bit due to exams.
can you please assign me this issue so that 2 people don't end up investing time on the same? 
Also, I will complete the task by 20, May. would it be alright?

**Comment by Shreyas-SAS** [comment]
@llaske Can you please add me to the discord channel, I am not able to view them from the link. Maybe it is a private server.

**Comment by llaske** [comment]
You can get the link to join the Discord on the Sugarizer web site

**Comment by llaske** [comment]
Expected UI is describe here https://github.com/llaske/sugarizer/issues/1356
