### ISSUE TITLE
Choosing images when connecting to a server is not descriptive enough

### ISSUE THREAD

**Issue by cjustinobi** [llaske/sugarizer#1353]
I think it should be stated in the UI that the images chosen during setup will be required for login. Some users may not be aware that the images they select during this step are necessary for future logins.

**Current Description**

![choosing images](https://user-images.githubusercontent.com/5602693/230769937-69248038-cad5-4d9f-be60-b61fbdaec086.png)

**Proposed Description**

![Expected UI](https://user-images.githubusercontent.com/5602693/230770454-05ea1660-c467-40a5-9aaa-bc0bdbded7e4.png)

**Comment by llaske** [comment]
We tend to limit text because Sugarizer users are children and sometimes they can't read.
Most of the time the concept of passwords is explain by teachers/parents.
Plus, there is a dedicated help message on the login screen.

![image](https://user-images.githubusercontent.com/981841/230867651-1a595ec7-eaf3-490e-8edb-a5c8ae348e22.png)

So we don't need to change the message.
