### ISSUE TITLE
Adding more colour choices to Gridpaint Activity

### ISSUE THREAD

**Issue by Niyatizzz** [llaske/sugarizer#1671]
**Description**
Currently, the grid paint activity offers a limited selection of colors for children to use while painting. To enhance creativity and engagement, it would be beneficial to add a wider variety of colors. Additionally, displaying the name of the color when a user hovers over it can help children learn color names and improve their vocabulary.

**Proposed Changes**

_Color Palette Expansion:_
Introduce a more extensive color palette, including primary, secondary, and shades (e.g., light blue, dark green).
Allow users to select colors from a color picker for even more customization.

_Hover Color Name Display:_
Implement a tooltip feature that displays the color name when the user hovers over a color in the palette.
Ensure the tooltip is clear and easy to read, providing a positive learning experience for children.

**Comment by llaske** [comment]
The GridPaint activity is for younger children. It should stay as simple as possible.
I don't think adding a color palette is interesting.
The Hover event is useless in Sugarizer because it's use most of the time on touch devices where there is nothing like Hover.
Plus writing color name is not appropriate for younger children that don't know how to read.

**Comment by Niyatizzz** [comment]
Yes i see your point, ill be closing this issue
