### ISSUE TITLE
Add easy to access UNDO feature to improve UX

### ISSUE THREAD

**Issue by kunal-mohta** [llaske/sugarizer#183]
This is not a major issue, but can help to improve the User experience.
Undo feature, using the conventional `Ctrl+Z` to **Paint**, **Grid Paint** and **Labyrinth JS**, can be considered to be added.

**Comment by llaske** [comment]
Paint and LabyrinthJS activities already include undo/redo feature with toolbar buttons.
GridPaint do not but I don't think it's very useful for this activity because it's very simple to undo an action manually and I think that this activity should be as simple as possible.
I'm not a big fan of using keyboard shortcut because Sugarizer is not at all mainly focus for keyboard. It's mainly focus for touch/mouse.

**Comment by kunal-mohta** [comment]
Oh, I completely understand.
