### ISSUE TITLE
Text overflows in Shared notes activity

### ISSUE THREAD

**Issue by Scar26** [llaske/sugarizer#333]
![notes](https://user-images.githubusercontent.com/41830515/55430520-f9c95280-55ab-11e9-8ff3-a9a22fad328f.gif)

**Comment by ashish0910** [comment]
@Scar26 That occurs because you are entering a single word of such a long length which I dont think will be entered by user practically . However when you add a paragraph it does not overflow . 

![Screenshot 2019-04-03 at 5 33 52 PM](https://user-images.githubusercontent.com/30404493/55477461-c2ec4e80-5636-11e9-96bb-ab1df3d37914.png)

**Comment by Scar26** [comment]
Still I think it's worth looking into

**Comment by llaske** [comment]
@ashish0910 is right, it's not really a bug because it's not a real use case.
BTW why not trying to fix if there is an elegant way to solve the issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/667

**Comment by llaske** [comment]
Revert back the fix in https://github.com/llaske/sugarizer/commit/f198b27f610bc1a0ca059a9297ae2d36cfceca61
It's incompatible with iOS: display issues when drawing cards.
The cure would be worse than the disease!
