### ISSUE TITLE
Sound don't restart in FoodChain activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#360]
Step to reproduce:
- Launch a new instance of FoodChain activity
- Click to launch the build game
- Cards appears and sounds are playing on each card
- Do nothing and stop the activity
- Reopen the FoodChain activity, the latest context is displayed
- The first card appears but not sound is played and the second card never appears

**Comment by utkarsh-raj** [comment]
After a bit of testing, I think that some API call is returning "en-GB" instead of "en" for the language code when the activity is reloaded. When we reload the activity, pause and play it, the error is gone the the activity functions as expected to.

I could identify two potential solutions. First, the en folder in audio can be safely renamed as en-GB, and I could test all the functions positively after this. Second, is to identify all the locale calls and see which is giving different codes, and maybe do a small hack to return the hardcoded "en" string instead to "en-GB".

Thoughts ?

**Comment by Hemansh31** [comment]
@llaske I have tried to resolve this issue and another issue that is when we go to home from a certain activity and then stop the activity and reopening the activity does not lead to home. (shown in GIF in PR #648

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/648
