### ISSUE TITLE
Improve responsiveness of toolbar in Write Activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#572]
In order to display all buttons in toolbar in Write activity, minimum width should be nearly 1032 px. Devices with width less than it cannot access all the features.
For an instance, undo and redo functionality in below is not accessible.
![ss of write activity](https://user-images.githubusercontent.com/42293606/72870874-564e5780-3d0f-11ea-86f4-fe2ebc1e9c0e.PNG)

**Comment by sarthak-g** [comment]
We can create dropdown menu and list all the hidden buttons according to screen width  in it.

**Comment by llaske** [comment]
You're right, activities with lot of buttons on the toolbar could have hidden buttons on small screens like small tablets or smartphones. It's why we try to put the most important features to the left of the toolbar and it's why we use media queries to ensure the stop button will always be visible.
BTW it's not very useful to use Write activity on a small tablet or a smartphone because a large part of the screen is already fill by the software keyboard.  So I'm not sure it make sense to add complexity to the activity to solve it. Plus, adding a long drop down menu will not be very practical on a small screen.

**Comment by sarthak-g** [comment]
> 
>
> BTW it's not very useful to use Write activity on a small tablet or a smartphone because a large part of the screen is already fill by the software keyboard.

Yeah, you're right.
