### ISSUE TITLE
alert "user already exists" should come earlier 

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#580]
When logging for the first time , a person need to choose images and colors before he gets to know that the user exists , so he would have to do all the procedure once again. I think that the new user should get to know in the first page where he enters his name whether the user already exists or not.

**Comment by llaske** [comment]
That's true. It could be improved.

**Comment by abhishektanwar** [comment]
@llaske @anshuldutt21 I am trying to reproduce the error but I am not able to do it . I cloned sugarizer:dev repository . Can I get some more information so that I can fix this error.Locally in my browser when I logoff a user and register another user with same username it doesn't give any error


![re](https://user-images.githubusercontent.com/40486188/75100036-bbd38380-55ee-11ea-8088-d8f9b7068915.gif)

**Comment by llaske** [comment]
@abhishektanwar , it happens only when you're connected to a server. Try on https://dev.sugarizer.org

**Comment by dhruvmisra** [comment]
@llaske, I want to propose a solution for this. When the user clicks 'Next' after entering name, we can POST the name along with a `beforeSignup` flag to the signup URL. A little modification in the signup method on the server will check this flag and use existing functions to validate the uniqueness of username. This would reuse existing routes and functions.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/786

**Comment by llaske** [comment]
Require fix https://github.com/llaske/sugarizer-server/pull/266 on server.
