### ISSUE TITLE
Measure Activity for Sugarizer

### ISSUE THREAD

**Issue by abhishektanwar** [llaske/sugarizer#709]
Developed the Measure activity of sugar for Sugarizer

**Comment by sarthak-g** [comment]
@llaske , I'm working on this activity and soon to issue a PR. I'm using p5.js but in p5.js we can take no. of samples for frequency in power of 2 between 32 and 32768. Due to this, for zoom in and zoom out functionality, we have to use freq/div to be in multiplication of 2. 
So it is acceptable if we use 24 Hz/div and then on next increase it becomes 48(= 24*2) Hz/div.

**Comment by llaske** [comment]
@sarthak-g is a good idea to work on this activity. I'm precisely thinking to add the activity in the GSoC idea list.
Plus the current proposed implementation in https://github.com/llaske/sugarizer/pull/708 is not complete.
But in my mind, the major issue is not regarding frequency but regarding Android/iOS compatibility.
All activities must work on all Sugarizer platforms so the big question is how to capture sound into Cordova because it can't be captured directly by the web container. I'm thinking to use the [Cordova Audio Input plugin](https://github.com/edimuj/cordova-plugin-audioinput) but we should demonstrate that it could work and it could mean that usage of p5.js will be difficult.

**Comment by sarthak-g** [comment]
@llaske , how can I test activity on android and ios?

**Comment by llaske** [comment]
@sarthak-g the easiest way is to test on Android is to use [Sugarizer APK builder](https://github.com/llaske/sugarizer-apkbuilder)

**Comment by sarthak-g** [comment]
@llaske , I've tested plugin in android device and ios simulator. It's working great as standalone. I don't think we have to use p5.js as AnalyserNode in Javascript give both time domain and freq domain data.
Your views?

**Comment by llaske** [comment]
@sarthak-g Good news! 
I'm agree with you.
I guess @abhishektanwar used it because he retrieved an existing sample p5.js sample that match a part of Measure activity. But we don't need p5.js: simple is better.

**Comment by sarthak-g** [comment]
@llaske , how do you test DC settings of measure activity. When I'm running measure activity (in sugar) on laptop, it doesn't show dc settings as displayed in below image:
![measureActivityImage](https://user-images.githubusercontent.com/42293606/110670805-ccec3400-81f3-11eb-973b-b4e9dbbb7529.png)

**Comment by llaske** [comment]
Hmmm. Don't know. May be it's reserved to the XO laptop. I suggest you to ask the question on the sugar-devel mailing list.

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/pull/957
