### ISSUE TITLE
Fullscreen icon changes in Jappy Activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#779]
![ezgif com-video-to-gif(8)](https://user-images.githubusercontent.com/42293606/78419265-c2c7ca00-7661-11ea-85a9-0facb198eea0.gif)

**Comment by llaske** [comment]
Not sure to understand the problem. The icon is fine.

**Comment by AndreaGon** [comment]
It seemed as though the fullscreen icon changes when clicked from this icon:
![image](https://user-images.githubusercontent.com/44361130/78516622-d05d8b00-77ec-11ea-9f1e-8926252f5c47.png)

Into this:
![image](https://user-images.githubusercontent.com/44361130/78516650-e8350f00-77ec-11ea-9818-c8cb1fc00023.png)

@sarthak-g I think, the first icon means that you execute the Jappy program in fullscreen mode, and when you switch to unfullscreen mode, the icon changes because the program is still running (notice the "Break Execution" button), thus giving the user a choice to return to fullsreen mode without re-executing the program.

**Comment by sarthak-g** [comment]
@AndreaGon you're right. I misunderstood it. Thank you for clarification.
