### ISSUE TITLE
Enhancement in multiplayer mode of Memorize activity

### ISSUE THREAD

**Issue by sarthak-g** [llaske/sugarizer#795]
1. Game stuck if one among the two users playing the game left. Although the game starts again if a new user joins.
Suggestion: Game should continue like the single-player mode until new user joins.
2. Reset button should be disabled in between the game. Otherwise, the user who is losing the game can press it.

**Comment by quozl** [comment]
First issue I agree with.

Second issue I'm ambivalent about.  Learning software need not attempt to implement social controls, because the environment the software is used in already has a strong social control system that needs challenges like this for learning to occur.  As long as it is quite clear _who_ pressed the reset button, I'm fine with it.

**Comment by sarthak-g** [comment]
> Second issue I'm ambivalent about. Learning software need not attempt to implement social controls, because the environment the software is used in already has a strong social control system that needs challenges like this for learning to occur. As long as it is quite clear _who_ pressed the reset button, I'm fine with it.

I understood your point. Thank you!

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/952
