### ISSUE TITLE
Feature to add a background to Shared Notes activity

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#799]
It could be nice to add a feature to set the background of the Shared Notes activity.
Currently the background is just white.

![image](https://user-images.githubusercontent.com/981841/81390006-073ffd00-911b-11ea-8e9d-93c2943ce4c6.png)

This new feature should:

- [ ] Add a new icon in the toolbar to select the background from the Journal
- [ ] Set the image as the background
- [ ] Handle resizing of the background image when the board is resized
- [ ] Handle record of the background image when the board is save in the Journal.

**Comment by ricknjacky** [comment]
@llaske I have tried my hand at this, the new behavior is:-
![ezgif-2-5130c683c1ac](https://user-images.githubusercontent.com/50985033/102658010-c0c87b80-419c-11eb-9a31-0f777d1c53c6.gif)

I am not sure if this matches the expected behavior. As you can see at the end when I add note two notes get added, I am kind of stuck as to why that is happening ;-;  I fondly anticipate your feedback on this and guidance on how to troubleshoot that error.

**Comment by llaske** [comment]
I don't think two notes are added. It look like the control use to set input text is not at the right place: both should be at the same place.

**Comment by ricknjacky** [comment]
Adding a background and Handling of zoom I've already shared in the previous comment.
Coming to the issue of drag, I had this misconception of dragging the image inside of canvas, hence the grey area in previous comment's gif.


![Sugar](https://user-images.githubusercontent.com/50985033/102687948-32460f80-4219-11eb-8cdc-ce0b15d4128d.gif)


Does this now satisfy the behavior expected?

**Comment by llaske** [comment]
The grey area is not an issue. It's normal to have a grey (or white) area at some point when the board is moved outside the background image. But the background should move when board is moved.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/914
