### ISSUE TITLE
Export palette in Write activity pop at the wrong place

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer#807]
Steps to reproduce:
- Launch Write activity with the Export palette not visible (because the screen is too small)
- Resize the screen to view the Export palette
- Click on the Export palette, it's displayed at the left of the screen 

![Peek 24-05-2020 17-06](https://user-images.githubusercontent.com/981841/82757548-6ff8cc00-9de1-11ea-98c0-657843de1fe6.gif)

**Comment by prakashujjwal1010** [comment]
Well, I found this bug not only in write activity but also in other activities.
this bug is occuring because the updatePosition for palette is not getting called on every click for toolbuttons.
 see the code from `palette.js` of sugar-web library

`        invoker.addEventListener('click', function (event) {
            if (!that.invoker.classList.contains("toolbutton")) {
                updatePosition(event.x, event.y);
            }
            that.toggle();
        });`

### Solution
we can change the code of `palette.js` to 
`invoker.addEventListener('click', function (event) {
            if (!that.invoker.classList.contains("toolbutton")) {
                updatePosition(event.x, event.y);
            }
            else {
              updatePosition();
            }
            that.toggle();
        });`

so just wants to ask is there any problem in changing sugar-web lib code And should we change  it in other activities also?

**Comment by quozl** [comment]
If you fix it please also do so in https://github.com/sugarlabs/sugar-web

**Comment by llaske** [comment]
Hmmm. First send a PR for Write, then we could extend it to sugar-web in all activities.
Which activities have you tested?

**Comment by prakashujjwal1010** [comment]
I have tested Paint activity , Physics activity, constellation
see below for physics activity,
![ezgif com-video-to-gif (13)](https://user-images.githubusercontent.com/40318927/83169009-0570c480-a130-11ea-9197-63691a877421.gif)

basically it will occur when the palette's position or display property gets changed.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/808
