### ISSUE TITLE
No Tutorial in Get Things Done Activity

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer#918]
![Screenshot from 2021-01-03 10-40-32](https://user-images.githubusercontent.com/60233336/103472673-ffbe1a00-4db5-11eb-988a-67d5570bb0ff.png)

Without a tutorial Get Things Done activity looks different from the rest of the activities of sugarizer.

**Comment by llaske** [comment]
Hmmm. Honestly I think that a tutorial for this activity is useless. The UI speak by itself.
Your PR is a clear evidence of it: only two sentences to explain how it works.

**Comment by saurabhhere** [comment]
Yes, you're right that UI explains it itself but when I used this activity after using other activity its top bar attracts my attention first as it is the activity not having a help button, it is a button that I as a user expecting consistent in all activities. Even if it does not seem useful to you as a tutorial, I think as a user it improves my experience while using the activity to some level.
Also in the future, if we add any other features or buttons we can directly add them to the existing tutorial if there is one, so I thought to add one.

**Comment by llaske** [comment]
I'm not sure it's better to have a consistent UI versus a more simple UI. I think simple is better. For the same reason there is no fullscreen button in this activity because it will be useless.
Regarding the future, to be honest, I'm not sure that the Get Things Done activity will be there in future Sugarizer versions. There is no clear evidence of the usage of this activity on the field.

**Comment by saurabhhere** [comment]
Okay, I understood your point. Thanks for the explanation.
I am closing this issue and PR #919
