### ISSUE TITLE
why react and vue both framwork used in this project?

### ISSUE THREAD

**Issue by rahulkiller104** [llaske/sugarizer#958]
it also possible with only react.

**Comment by llaske** [comment]
It's intentional. As explain [here](https://github.com/llaske/sugarizer/blob/dev/docs/architecture.md) each activities are independent and can use its own framework. Some activities use ReactJS, some activities use Vue.js, most activities are written with VanillaJS only.
It's important to let developers use its favorite framework.

**Comment by rahulkiller104** [comment]
@llaske  thank you for explanation
