### ISSUE TITLE
Improving the UX of desktop toolbar

### ISSUE THREAD

**Issue by ishubham21** [llaske/sugarizer#979]
![Screenshot from 2022-02-19 13-33-17](https://user-images.githubusercontent.com/34435822/154792611-b380b697-8e43-4db0-ab30-a0e7510e1dde.png)

1. There are two different buttons to toggle between list-view and radial-view. Wouldn't it be nice to have a single button (say `toggle list view`) that would do the task? We can update the icon with each toggle too. 
2. Currently the search bar is oddly placed, it can be moved more towards the left so that it looks evenly placed. In fact, how about we use flex-box to position all the times in the toolbar, which would eliminate the effort of styling using `position: absolute` for each screen?

**Comment by ishubham21** [comment]
> ![Screenshot from 2022-02-19 13-33-17](https://user-images.githubusercontent.com/34435822/154792611-b380b697-8e43-4db0-ab30-a0e7510e1dde.png)
> 
> 1. There are two different buttons to toggle between list-view and radial-view. Wouldn't it be nice to have a single button (say `toggle list view`) that would do the task? We can update the icon with each toggle too.
> 2. Currently the search bar is oddly placed, it can be moved more towards the left so that it looks evenly placed. In fact, how about we use flex-box to position all the times in the toolbar, which would eliminate the effort of styling using `position: absolute` for each screen?

cc: @llaske

**Comment by llaske** [comment]
@ishubham21 thanks for these suggestions.

1. I'm not in favor of replacing the two buttons Radial/List by a toggle button. This behavior is inherited from Sugar and I think it's easier for children to see all possibilities in two buttons. The toggle button concept is not so easy to understand.
2. I'm not sure what you mean by oddly placed for the Search bar. It should not be too far to the left because on tablet the the user's finger may touch the edge. BTW you're agree on the current implementation, it could be improved. It's something plan for the next Sugarizer version based on Vue.js.

**Comment by ishubham21** [comment]
Okay, I guess I should close this issue in this case.
