### ISSUE TITLE
Story activity horizontal is unresponsive 

### ISSUE THREAD

**Issue by Shivansh2287** [llaske/sugarizer#989]
@llaske  in story activity horizontal scroll is unresponsive and I have fixed the issue 
![issue](https://user-images.githubusercontent.com/54775060/156635299-7b53795a-99e6-4ff9-85da-f62ec6ac5c03.png)

**Comment by llaske** [comment]
Hmmmm. Could you explain in which case you've got this behavior?
Sugarizer is not responsive for any Window size. See [here](https://github.com/llaske/sugarizer/issues/422) for more.

**Comment by Shivansh2287** [comment]
while checking the responsiveness of the story activity it breaks at  647px and body content is too big for the screen so I changed the overflow property in the media query 



![issue3](https://user-images.githubusercontent.com/54775060/156688876-1ed9aca9-c311-48eb-9ef2-eb6e63da7533.png)

**Comment by llaske** [comment]
@Shivansh2287 It's not a realistic size. The minimum supported screen size is iPhone 6/7/SE.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/981841/156842086-8a1b2483-c406-44cc-b578-d5e06d203c7d.png">

And even in this case the activity will be complex to use due to the virtual keyboard.

**Comment by Shivansh2287** [comment]
Ok so I am closing the issue
