### ISSUE TITLE
Make new activity

### ISSUE THREAD

**Issue by dhwaj1902** [llaske/sugarizer#999]
Hi mentors, may I work on a new activity for children, i.e. a snake game.

**Comment by llaske** [comment]
Hi @dhwaj1902, Everyone is free to write Sugarizer activities because it's easy to customize the app to include its own activities.
BTW activities packaged in Sugarizer should have a pedagogical goal.
It will not be the case for a snake game.

**Comment by dhwaj1902** [comment]
Sure @llaske can you suggest me some of the activites which would be helpfull for the org that I can make?

**Comment by Shreyas-SAS** [comment]
@dhwaj1902 @llaske If I may suggest, why not create a dictionary game where if the user chooses correct meaning of the word displayed in given time he earns points. since the users will be children we can keep the words simple and easy. that way they can learn a lot.

@dhwaj1902 If you wish we can collaborate on this after @llaske sir gives us the permission. 

I wanted a start point to work on the repo since I want to work on 2 of the projects here that have been listed on GSOC. this may just be the starting point. What do you say?

**Comment by llaske** [comment]
@dhwaj1902 No new activities has been asked by the field recently.
@Shreyas-SAS It's basically what's possible in Abecedarium.

You could try to work on a critical issue regarding DollarStreet activity : https://github.com/llaske/sugarizer/issues/985

**Comment by Shreyas-SAS** [comment]
@llaske Oh. I didn't know about Abecedarium's features. I am really sorry for troubling you and thank you for the suggestion. I will definitely try my best to do whatever I can. Sorry again.

**Comment by dhwaj1902** [comment]
ok, @llaske will try #985 issue.
